name: Run AgentAI Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Keep this at a specific version, e.g., '3.12' or '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run AgentAI Script
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        BROWSER_USE_HEADLESS: 1
        BROWSER_USE_TELEMETRY_ENABLED: 0
      run: |
        # --- THIS IS THE CRUCIAL CHANGE ---
        python -m src.agent_core.agent_runner
        # ----------------------------------